### ISSUE TITLE
Doom for Quest?

### ISSUE THREAD

**Issue by GitGitHubUser** [DrBeef/DoomGVR#2]
Hi,
many thanks for your awesome ports of Doom and Quake!!!
Any chance you will also release a Quest-optimized version of Doom? ;)
Many thanks in advance!

**Comment by SlipSlot** [comment]
I know Doom isn't true 3D so playing in VR isn't necessarily a decent experience, but just mapping the touch controller buttons would be enough for us to at least give it a go out of morbid curiosity. Please at least bring this update for us Quest users.

**Comment by BenMcLean** [comment]
Making a truly 3D version of Doom playable in VR on the Oculus Quest is quite possible. [GZDoom](https://zdoom.org/) would probably be the most convenient modern source port to start such an effort from.

In the meantime, DoomGVR might possibly work on the Quest if you add a bluetooth game controller.

**Comment by DrBeef** [comment]
I had a look at the effort involved wasn't worth it for the sub-par experience that DoomGVR would provide. So I won't be updating this version any further. 

However, as @BenMcLean suggested, I intend to look at making a new port using GzDoom (or similar).
