### ISSUE TITLE
What should I do to make it work ?

### ISSUE THREAD

**Issue by Morgan-6Freedom** [DrBeef/DoomGVR#3]
Hello.
I used Sidequest to push DoomGVR to my quest.
When I launch it, I only have a music with a rotating logo.

What should I do to make it work ?
Should I put a .wad somewhere ?

Thank you

**Comment by DrBeef** [comment]
At the moment this doesn't have Touch Controller support. It is something I am going to add at some point, but this is simply the version that was done for GearVR/OculusGo that also happens to work on the Quest if you have a pair bluetooth gamepad. If you don't have one then I would suggest you hang on for now.
